# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks - `relative_permalinks` ensures post links from the index work properly
permalink:           pretty
relative_permalinks: true

# Setup
#title:               Lanyon
tagline:             ' //from engineers, for engineers'
#baseurl:             /
paginate:            5

# About/contact
author:
  name:              Computing @ Monsanto.com
  url:               "http://computing.monsanto.com"
  email:             computing@monsanto.com


# Site settings
title: Computing
email: computing@monsanto.com
description: > # this means to ignore newlines until "baseurl:" 
  The engineers of Monsanto produce code that powers agricultural products that support farmers all around the world. Our goal of sustainable agriculture mirrors the way we present our ideas and code to the world.
url: "http://computing.monsanto.com"
twitter_username: MonsantoCo
github_username: MonsantoCo
site.github.repo: github.com/MonsantoCo/computing.monsanto.com

# Custom vars
version:             1.0.0
