# Site settings
title: Engineering at Monsanto
#header-img: img/home-bg.jpg
#header-img: img/mon-hello-1.jpg
header-img: img/mon-field_rows.jpg
email: engineering@Monsanto.com
description: "The engineers of Monsanto produce code that powers agricultural products that support farmers all around the world. Our goal of sustainable agriculture mirrors the way we present our ideas and code to the world."
baseurl: ""
url: "http://engineering.monsanto.com"
twitter_username: MonPlatformEng
youtube_username: MonsantoCo
github_username:  MonsantoCo
facebook_username: MonsantoCo

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/rss.xml"
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"#
