# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
#title:               Lanyon
tagline:             ' ~ a blog from the engineers at Monsanto'
#description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
#url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Computing @ Monsanto.com
  url:               "http://computing.monsanto.com"
  email:             computing@monsanto.com

# Custom vars
version:             1.0.0

# Site settings
title: computing.monsanto.com
email: computing@monsanto.com
description: > # this means to ignore newlines until "baseurl:" 
  The engineers of Monsanto produce code that powers agricultural products that support farmers all around the world. Our goal of sustainable agriculture mirrors the way we present our ideas and code to the world.
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://computing.monsanto.com" # the base hostname & protocol for your site
twitter_username: MonsantoCo
github_username: MonsantoCo

site.github.repo: github.com/MonsantoCo/computing.monsanto.com

# Build settings
#markdown: kramdown
